<?php

// MMDB ASN Blocklist

// case insensitive

$mmdb_ASN_array = [
"alicloud",
"alibaba cloud",
"digitalocean",
"digital ocean",
"kwaifong group limited",
"contabo",
"leaseweb",
"hostroyale technologies",
"ucloud information",
"secure internet llc",
"inios oy",
"fnk llc",
"dedipath-llc",
"mirholding b.v.",
"datacamp limited",
"voxility llp",
"lucidacloud",
"cloud computing corporation",
"gigabit hosting",
"hetzner online",
"m247 europe srl",
"incognet llc",
"ponynet",
"as40676",
"nforce entertainment b.v.",
"trabia srl",
"latitude-sh",
"dataforest gmbh",
"31173 services ab",
"advin services llc",
"wholesale services provider",
"netminders",
"altushost b.v.",
"amazon-02",
"akamai connected cloud",
"uab cherry servers",
"datema bilisim ticaret anonim sirketi",
"alibaba us technology co., ltd.",
"netcup gmbh",
"jinx co., limited",
"fd-298-8796",
"cloudsingularity",
"weserve b.v.",
"amarutu technology ltd",
"limestonenetworks",
"versija sia",
"oy crea nova hosting solution ltd",
"owl limited",
"tzulo",
"serverastra kft",
"ionos se",
"as-globaltelehost",
"estnoc oy",
"as-colocrossing",
"greenhost bv",
"keminet shpk",
"worldstream b.v.",
"aeza international ltd",
"asline limited",
"packethub s.a.",
"gorillaservers",
"as-vultr",
"nl-811-40021",
"cheapy-host",
"jsc selectel",
"gb network solutions sdn. bhd.",
"latitude.sh",
"limestone networks, inc",
"scaleway",
"m247 europe",
// above default entries from Matomo Plugin TrackingSpamPrevention
// https://github.com/matomo-org/plugin-TrackingSpamPrevention/blob/5.x-dev/BlockedGeoIp.php
"twitter",
"business",
// "deutsche telekom global business solutions",
// "vodafone germany business",
// "bell canada business",
"fastly",
"logicweb",
"dataport",
"cityfibre",
"cox communications",
"terratransit",
"gtt communications inc",
"amazon.com",
"vultr",
"fiber optical network",
"google virtual private cloud",
"asadov ruslan rafaelevich",
"contact consumers",
"spectrum networks",
"cisco opendns",
"zayo bandwidth",
"ace data centers",
"bite lietuva",
"oculus networks",
"ovh sas",
"sprious",
"web2objects",
"zayo bandwidth",
"db systel",
"gsl networks",
"ecotel communication",
"uk-2 limited",
"informacines sistemos ir technologijos",
"glesys ab",
"bwi gmbh",
// "Telefonica", // TESTPOINT
"last entry without trailing comma"
];

?>